language: python
python:
    - "2.7"

install:
    - pip install --user -r requirements.txt

script:   
    - make

after_success:
    - coverage run --source=unittest test_rpn.py test
    - coveralls

